version: '3.5'

services:

    backend:
        image: backend-2-2
        build:
            context: .
            dockerfile: DockerfileBackend
        volumes:
            - ./logs.txt:/exercise/logs.txt:rw
        ports:
            - 8000:8000
        environment:
            - FRONT_URL=http://localhost:5000
            - REDIS=redis
        container_name: backend-2-2
        depends_on:
            - redis

    frontend:
        image: frontend-2-2
        build:
            context: .
            dockerfile: DockerfileFrontend
        ports:
            - 5000:5000
        environment:
            - API_URL=http://localhost:8000
        container_name: frontend-2-2

    redis:
        image: redis
        container_name: redis-2-2
